import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Nunito } from "next/font/google";
import "../globals.css";
import { Header } from "@/components/shared/Header";



export const metadata: Metadata = {
  title: "Next Pizza",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
     modal
}: Readonly<{ 
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
        <main className='min-h-screen'>
          <Header/>
        {children}
        {modal}
        </main>
      
  );
}
