import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Nunito } from "next/font/google";
import "../globals.css";
import { Header } from "@/components/shared/Header";
import { ProductModalProvider } from "@/context/ProductModalContext";
import { ProductModal } from "@/components/shared/modals/ProductModal";

export const metadata: Metadata = {
  title: "Next Pizza",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children
}: Readonly<{ 
  children: React.ReactNode;
}>) {
  return (
    <ProductModalProvider>
      <main className='min-h-screen'>
        <Header/>
        {children}
        <ProductModal />
      </main>
    </ProductModalProvider>
  );
}

